config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  namespace :posts do
    resources :searches, only: :index
  end
  resources :posts do
    resources :comments, only: :create
    get "search"
  end
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, :user_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :post

  validates :src, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :posts_tags
  has_many :tags, dependent: :destroy, through: :posts_tags
  accepts_nested_attributes_for :tags, allow_destroy: true
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :favorites, allow_destroy: true
  has_many :iine_users, through: :favorites, source: :user

  validates :name, :text, presence: true

  def self.search(search)
    return Post.all unless search
    Post.joins(:tags).where('tags.text LIKE(?)', "%#{search}%")
  end

  # postをいいねする
  def iine(user)
    favorites.create(user_id: user.id)
  end

  # postのいいねを解除する
  def uniine(user)
    favorites.find_by(user_id: user.id).destroy
  end

  # 現在のユーザーがいいねしてたらtrueを返す
  def iine?(user)
    iine_users.include?(user)
  end

end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts_tags
  has_many :posts, through: :posts_tags

  validates :text, presence: true

  def self.search(search)
    return Tag.all unless search
    Tag.where('text LIKE(?)', "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :favorites, allow_destroy: true

  validates :nickname, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = Post.find(params[:post_id])
      render "posts/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.iine(current_user)
  end

  def destroy
    @post = Favorite.find(params[:id]).post
    @post.uniine(current_user)
  end
end

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  def index
    @keyword = params[:keyword]
    @posts = Post.search(@keyword)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, except: [:index, :new, :create]

  def index
    @posts = Post.all.includes(:images).order("created_at DESC")
  end

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      flash.now[:alert] = "商品を削除できませんでした"
      render :show
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  private

  def post_params
    params.require(:post).permit(:name, :tag, :text, images_attributes: [:id, :src, :_destroy], tags_attributes: [:text]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts/searches_helper.rb
module Posts::SearchesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/favorites/_favorite.html.haml
- if !current_user?(post.user)
  %span.favorite
  - if post.iine?(current_user)
    = form_for(post.favorites.find_by(user_id: current_user.id), method: :delete, remote: true) do |f|
      = button_tag(class: "btn btn-default btn-xs") do
        = content_tag :span, "#", class: "glyphicon glyphicon-heart"
  - else
    = form_for(post.favorites.build, remote: true) do |f|
      = hidden_field_tag :post_id, post.id
      = button_tag(class: "btn btn-default btn-xs") do
        = content_tag :span, "#", class: "glyphicon glyphicon-heart-empty"

app/views/favorites/create.html.haml
%h1 Favorites#create
%p Find me in app/views/favorites/create.html.haml

app/views/favorites/destroy.html.haml
%h1 Favorites#destroy
%p Find me in app/views/favorites/destroy.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SakePairing
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .header
    .header__innner
      .header__left
        .header__left__icon
          = link_to root_path do
            = image_tag "/logo.png", class: "header__left__icon__img", alt: ""
        .header__left__text
          = link_to root_path, class: "header__left__text__text" do
            SAKE PAIRING
      .header__right
        %ul.header__right__list
          - if user_signed_in?
            = link_to user_session_path, class: "header__right__list__login" do
              マイページ
            = link_to new_post_path, class: "header__right__list__post" do
              投稿する
            = link_to destroy_user_session_path, method: :delete, class: "header__right__list__logout" do
              ログアウト
          - else
            = link_to new_user_session_path, class: "header__right__list__login" do
              ログイン
            = link_to new_user_registration_path, class: "header__right__list__new" do
              新規登録
            = link_to new_post_path, class: "header__right__list__post" do
              投稿する
  = yield

app/views/posts/_form.html.haml
.post__contents
  .post__container
    = form_with model: @post, local: true, class: "post__new" do |f|
      .post__left
        #image-box
          #previews
            - if @post.persisted?
              - @post.images.each_with_index do |image, i|
                .preview-box{data: {index: i}}
                  = image_tag image.src.url, class: :"img-box", data: { index: i }
                  .lower-box
                    %label{for: "post_images_attributes_#{i}_src", class: "update-box"} 変更
                    .js-remove 削除
            .label
              %label{for: "post_images_attributes_#{@post.images.count}_src", class: "label-box", id: "label-box__#{@post.images.count}"}
                .label-box__text ファイルをアップロード
          = f.fields_for :images do |image|
            .js-file_group{"data-index": "#{image.index}"}
              = image.file_field :src, class: "js-file"
            - if @post.persisted?
              = image.check_box :_destroy, data:{ index: image.index }, class: "hidden-destroy"
          - if @post.persisted?
            .js-file_group{"data-index": "#{@post.images.count}"}
              = file_field_tag :src, name: "post[images_attributes][#{@post.images.count}][src]", class: "js-file"
      .post__right
        = f.text_field :name, placeholder: "銘柄", class: "post__right__type"
        = f.fields_for :tags, @post.tags.build do |t|
          = t.text_field :text, placeholder: "このお酒に合う料理は？", class: "post__right__tag"
        = f.text_area :text, placeholder: "コメント",  class: "post__right__comment"
        .post__button
          = f.submit "投稿する", class: "post__btn"

app/views/posts/_post.html.haml
//商品一覧表示
- @posts.each do |post|
  .post-list
    = link_to post_path(post.id), class: "post-list__content" do
      .post-list__card
        - post.images.each do |image|
          = image_tag image.src.url, class: "post-list__card__img"
        .post-list__lower-box
          .post-list__lower-box__name
            = post.name
          .post-list__lower-box__tag
            ＃
            - post.tags.each do |tag|
              = tag.text

app/views/posts/edit.html.haml
= render partial: 'form'

app/views/posts/index.html.haml
.main
  .top-visual
    .content
      .content__title
        あなたの飲みたい日本酒が見つかる
      .content__search
        = form_with url: posts_searches_path, method: :get, local: true do |f|
          = f.text_field :keyword, class: "content__search__input", placeholder: "今日の晩ごはんは？"
          = link_to image_tag "/icon-search 1.png", class: "content__search__btn"
.new-posts
  .head
    = link_to root_path, class: "post-head" do
      みんなが投稿したペアリング
    .post-lists
      = render "post"

app/views/posts/new.html.haml
= render partial: "form"

app/views/posts/searches/index.html.haml
.new-posts
  .head
    - if @keyword.present?
      = "#{@keyword}に合う日本酒"
    .post-lists
      = render "posts/post"

app/views/posts/show.html.haml
.details
  .detail-box
    .detail-box__heading
      = @post.name
    .detail-box__photo
      .detail-box__photo__wrap
        .detail-box__photo__sold
        = image_tag @post.images.first.src.url, alt: 'main_photo', class: :"detail-box__photo__main"
    .detail-box__user
      .detail-box__user__icon
        = link_to root_path, class: "detail-box__user__icon__face" do
          = icon("far fa-grin-wink", class: "detail-box__user__icon__img")
      .detail-box__user__name
        = @post.user.nickname
    .detail-box__description
      .detail-box__description__tag
        ＃
        - @post.tags.each do |tag|
          = tag.text
      .detail-box__description__text
        = @post.text
        = render "favorites/favorite", post: @post
    .detail-box__action
      = link_to edit_post_path(@post), class: :"detail-box__action__link" do
        .detail-box__action__button 投稿の編集
      = link_to post_path(@post), method: :delete, class: :"detail-box__action__link", data: {confirm: "削除しますか？"} do
        .detail-box__action__button.detail-box__action__button--gray この投稿を削除する
      // お気に入り 0
      -# = link_to '#', class: :"detail-box__button-container__report" do
      -#   = icon 'fa', 'flag'
      -#   不適切な商品の通報
  = form_with model: [@post, @comment], local: true, class: :"detail-comment" do |f|
    - if @comments
      - @comments.each do |comment|
        .detail-comment__wrap
          .detail-comment__left
            = image_tag 'neko_akai.png', alt: 'item_photo', class: :'detail-comment__icon'
          .detail-comment__right
            .detail-comment__nickname= comment.user.nickname
            .detail-comment__body
              = comment.body
    = f.text_area :body, class: :"detail-comment__textbox", placeholder: '気軽にコメントしましょう！'
    .detail-comment__button
      = button_tag type: 'submit', class: 'detail-comment__submit' do
        = icon 'fa', 'comment'
        コメントする
  .detail-category__posts
    .detail-category__posts__head